name: geoai
channels:
  - conda-forge
dependencies:
  - python=3.10
  - earthengine-api
  - adlfs>=2024.7.0
  - dask>=2024.11.2
  - fsspec>=2024.10.0
  - geopandas>=1.0.1
  - lonboard>=0.10.3
  - matplotlib>=3.9.2
  - planetary-computer>=1.0.0
  - pyarrow>=18.0.0
  - pystac-client>=0.8.5
  - xarray>=2024.11.0
  - zarr>=2.18.3
  - odc-stac>=0.3.10
  - rasterio>=1.4.2
  - rasterstats>=0.20.0
  - numpy>=2.1.3
  - pip
  - rioxarray
  - geemap
  - lightgbm
  - shapely
  - scikit-image
  - scikit-learn
  - tqdm
  - joblib